/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004c6e",
        "surface-bright": "#31394d",
        "on-primary-container": "#00302b",
        "on-secondary-fixed": "#001e2f",
        "on-secondary-container": "#00344e",
        "on-primary-fixed-variant": "#005049",
        "on-tertiary-container": "#0d0096",
        "surface-container-low": "#131b2e",
        "on-primary-fixed": "#00201d",
        "on-secondary": "#00344d",
        outline: "#879391",
        "on-tertiary-fixed": "#07006c",
        "on-surface-variant": "#bcc9c6",
        "surface-variant": "#2d3449",
        "on-error": "#690005",
        "surface-container": "#171f33",
        surface: "#0b1326",
        primary: "#6bd8cb",
        "tertiary-fixed": "#e1e0ff",
        "inverse-on-surface": "#283044",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-error-container": "#ffdad6",
        tertiary: "#c0c1ff",
        "secondary-fixed-dim": "#89ceff",
        "on-primary": "#003732",
        "primary-fixed": "#89f5e7",
        "primary-fixed-dim": "#6bd8cb",
        "on-surface": "#dae2fd",
        "on-tertiary": "#1000a9",
        background: "#0b1326",
        "inverse-primary": "#006a61",
        "secondary-container": "#00a2e6",
        "surface-container-lowest": "#060e20",
        "inverse-surface": "#dae2fd",
        "secondary-fixed": "#c9e6ff",
        "surface-container-high": "#222a3d",
        "surface-tint": "#6bd8cb",
        secondary: "#89ceff",
        "on-background": "#dae2fd",
        "error-container": "#93000a",
        "primary-container": "#29a195",
        error: "#ffb4ab",
        "tertiary-container": "#8083ff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-highest": "#2d3449",
        "outline-variant": "#3d4947",
        "surface-dim": "#0b1326",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        base: "4px",
        xs: "0.5rem",
        lg: "2rem",
        xl: "3rem",
        sm: "1rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        md: "1.5rem",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
